I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/event.rpy", line 9, in script
    init -2 python:
  File "game/scripts/event.rpy", line 10, in <module>
    default_fallback = Event(2, "default_fallback_event")
NameError: name 'Event' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/event.rpy", line 9, in script
    init -2 python:
  File "C:\Users\bigma\Documents\RenPy\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\bigma\Documents\RenPy\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/event.rpy", line 10, in <module>
    default_fallback = Event(2, "default_fallback_event")
NameError: name 'Event' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Mind the School 0.1.3
Mon Jan 29 15:32:36 2024
