I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script call
    call intro from _call_intro
  File "game/scripts/overview.rpy", line 737, in script
    if len(headmaster_proficiencies.keys()) < 2 and (IntroCondition(False)).is_fullfilled():
  File "game/scripts/overview.rpy", line 737, in <module>
    if len(headmaster_proficiencies.keys()) < 2 and (IntroCondition(False)).is_fullfilled():
AttributeError: 'IntroCondition' object has no attribute 'is_fullfilled'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script call
    call intro from _call_intro
  File "game/scripts/overview.rpy", line 737, in script
    if len(headmaster_proficiencies.keys()) < 2 and (IntroCondition(False)).is_fullfilled():
  File "C:\Users\bigma\Documents\RenPy\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\bigma\Documents\RenPy\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\bigma\Documents\RenPy\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/overview.rpy", line 737, in <module>
    if len(headmaster_proficiencies.keys()) < 2 and (IntroCondition(False)).is_fullfilled():
AttributeError: 'IntroCondition' object has no attribute 'is_fullfilled'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Mind the School 0.1.4C
Mon Sep  9 13:05:59 2024
