I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 485, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 485, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 509, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
PicklingError: Can't pickle <function is_replay at 0x00000000107e1280>: it's not the same object as store.is_replay

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00keymap.rpy", line 485, in script
    python hide:
  File "C:\Users\bigma\Documents\RenPy\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\bigma\Documents\RenPy\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 485, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 509, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "C:\Users\bigma\Documents\RenPy\renpy\loadsave.py", line 427, in save
    reraise(t, e, tb)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\bigma\Documents\RenPy\renpy\loadsave.py", line 413, in save
    dump((roots, renpy.game.log), logf)
  File "C:\Users\bigma\Documents\RenPy\renpy\compat\pickle.py", line 103, in dump
    pickle.dump(o, f, pickle.HIGHEST_PROTOCOL if highest else PROTOCOL)
PicklingError: Can't pickle <function is_replay at 0x00000000107e1280>: it's not the same object as store.is_replay

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Mind the School 0.1.3
Tue Mar 12 10:29:30 2024
